<?php

namespace OCA\Extract\Controller;

/**
 * SPDX-FileCopyrightText: 2025 LibreCode coop and contributors
 * SPDX-FileCopyrightText: 2026 IB Trieb GmbH & Co. KG
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

// Only in order to access Filesystem::isFileBlacklisted().
use OC\Files\Filesystem;
use OCA\Extract\ResponseDefinitions;

use OCA\Extract\Service\ExtractionService;
use OCA\Extract\Service\ProgressService;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Attribute\ApiRoute;
use OCP\AppFramework\Http\Attribute\NoAdminRequired;
use OCP\AppFramework\Http\DataResponse;
use OCP\Encryption\IManager;
use OCP\Files\Folder;

use OCP\Files\InvalidPathException;

use OCP\Files\IRootFolder;

use OCP\Files\NotFoundException;
use OCP\IL10N;
use OCP\IRequest;
use OCP\ISession;
use OCP\IURLGenerator;
use Psr\Log\LoggerInterface;

/**
 * @psalm-import-type ExtractFolder from ResponseDefinitions
 * @psalm-import-type ExtractProgress from ResponseDefinitions
 */
final class ExtractionController extends AEnvironmentAwareController {

	/**
	 * Shape of a job id the browser is allowed to hand us. It ends up in a cache
	 * key and a file name, so it is validated instead of sanitised.
	 */
	private const JOB_ID_PATTERN = '/^[A-Za-z0-9_-]{8,64}$/';

	/** @var Folder */
	private $userFolder;

	/** @var Array $mimeTypes */
	private array $mimeTypes = [
		'application/zip' => 'zip',
		'application/x-rar-compressed' => 'rar',
		'application/x-tar' => 'other',
		'application/x-7z-compressed' => 'other',
		'application/x-bzip2' => 'other',
		'application/x-deb' => 'other',
		'application/x-gzip' => 'other',
		'application/x-compressed' => 'other'
	];

	public function __construct(
		string $AppName,
		IRequest $request,
		private ExtractionService $extractionService,
		private ProgressService $progressService,
		private IRootFolder $rootFolder,
		private IL10N $l,
		private LoggerInterface $logger,
		private IManager $encryptionManager,
		private string $userId,
		private IURLGenerator $urlGenerator,
		private ISession $session,
	) {
		parent::__construct($AppName, $request);
		$this->userFolder = $this->rootFolder->getUserFolder($this->userId);
	}

	private function getFile(string $directory, string $fileName): string|false {
		$fileNode = $this->userFolder->get($directory . '/' . $fileName);
		return $fileNode->getStorage()->getLocalFile($fileNode->getInternalPath());
	}

	/**
	 * Register the new files to the NC filesystem.
	 *
	 * @param string $fileName The Nextcloud file name.
	 *
	 * @param string $directory The Nextcloud directory name.
	 *
	 * @param string $extractTo The local file-system path of the directory
	 *                          with the extracted data, i.e. this is the OS path.
	 *
	 * @param null|string $tmpPath The Nextcloud temporary path. This is only
	 *                             non-null when extracting from external storage.
	 */
	private function postExtract(string $fileName, string $directory, string $extractTo, ?string $tmpPath): void {

		$iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($extractTo));
		foreach ($iterator as $file) {
			/** @var \SplFileInfo $file */
			if (Filesystem::isFileBlacklisted($file->getBasename())) {
				$this->logger->warning(__METHOD__ . ': removing blacklisted file: ' . $file->getPathname());
				// remove it
				unlink($file->getPathname());
			}
		}

		$NCDestination = $directory . '/' . $fileName;
		if ($tmpPath !== null) {
			$tmpFolder = $this->rootFolder->get($tmpPath);
			$tmpFolder->move($this->userFolder->getFullPath($NCDestination));
		} else {
			// This seems to be enough to trigger a files-cache refresh
			$this->userFolder->get($NCDestination);
		}
	}

	/**
	 * The only AJAX callback. This is a hook for ordinary cloud-users, os no admin required
	 *
	 * @param string $nameOfFile Name of the file to be extracted
	 * @param string $directory Directory where the file is located
	 * @param bool $external Is the file located on an external storage?
	 * @param string $mime MIME type of the file
	 * @param string $jobId Id generated by the client to poll the progress of this extraction, empty to not report progress
	 * @return DataResponse<Http::STATUS_OK, array{code?: 0|1, desc?: string, extracted?: ExtractFolder}, array{}>|DataResponse<Http::STATUS_NOT_FOUND, array<empty>, array{}>
	 *
	 * 200: OK
	 * 404: Not found or invalid path
	 */
	#[ApiRoute(verb: 'POST', url: '/api/{apiVersion}/extraction/execute', requirements: ['apiVersion' => '(v1)'])]
	#[NoAdminRequired]
	public function execute(
		string $nameOfFile,
		string $directory,
		bool $external,
		string $mime,
		string $jobId = '',
	): DataResponse {
		$type = $this->mimeTypes[$mime];

		if ($jobId !== '' && preg_match(self::JOB_ID_PATTERN, $jobId) !== 1) {
			$jobId = '';
		}

		if ($jobId !== '') {
			// PHP holds an exclusive lock on the session file for the lifetime of
			// a request. Extracting a large archive takes minutes, and the
			// progress polls would queue up behind it, so the session is released
			// here - nothing below writes to it.
			$this->session->close();
			$this->progressService->start($this->userId, $jobId, $nameOfFile);
		}

		// Extracting a large archive easily outlives the default execution time.
		@set_time_limit(0);

		if ($this->encryptionManager->isEnabled()) {
			$desc = $this->l->t('Encryption is not supported yet');
			$this->failJob($jobId, $desc);
			return new DataResponse(['code' => 0, 'desc' => $desc]);
		}
		$file = $this->getFile($directory, $nameOfFile);
		if ($file === false) {
			$desc = $this->l->t('File not found');
			$this->failJob($jobId, $desc);
			return new DataResponse(['code' => 0, 'desc' => $desc]);
		}
		$dir = dirname($file);
		//name of the file without extension
		$fileName = pathinfo($nameOfFile, PATHINFO_FILENAME);
		$extractTo = $dir . '/' . $fileName;

		// if the file is an external storage
		if ($external) {
			$appPath = $this->userId . '/' . $this->appName;
			try {
				$appDirectory = $this->rootFolder->get($appPath);
			} catch (\OCP\Files\NotFoundException $e) {
				$appDirectory = $this->rootFolder->newFolder($appPath);
			}
			if (pathinfo($fileName, PATHINFO_EXTENSION) == 'tar') {
				$archiveDir = pathinfo($fileName, PATHINFO_FILENAME);
			} else {
				$archiveDir = $fileName;
			}

			// remove temporary directory if exists from interrupted previous runs
			try {
				$appDirectory->get($archiveDir)->delete();
			} catch (\OCP\Files\NotFoundException $e) {
				// ok
			}

			$tmpPath = $appDirectory->getPath() . '/' . $archiveDir;
			$extractTo = $appDirectory->getStorage()->getLocalFile($appDirectory->getInternalPath()) . '/' . $archiveDir;
		} else {
			$tmpPath = null;
		}

		$onProgress = $this->progressReporter($jobId);

		switch ($type) {
			case 'zip':
				$response = $this->extractionService->extractZip($file, $extractTo, $onProgress);
				break;
			case 'rar':
				$response = $this->extractionService->extractRar($file, $extractTo, $onProgress);
				break;
			default:
				// Check if the file is .tar.gz in order to do the extraction on a single step
				if (pathinfo($fileName, PATHINFO_EXTENSION) == 'tar') {
					$cleanFileName = pathinfo($fileName, PATHINFO_FILENAME);
					$extractTo = dirname($extractTo) . '/' . $cleanFileName;
					$response = $this->extractionService->extractOther($file, $extractTo, $onProgress);
					$file = $extractTo . '/' . pathinfo($file, PATHINFO_FILENAME);
					$fileName = $cleanFileName;
					$response = $this->extractionService->extractOther($file, $extractTo, $onProgress);

					// remove .tar file
					unlink($file);
				} else {
					$response = $this->extractionService->extractOther($file, $extractTo, $onProgress);
				}
				break;
		}

		if (($response['code'] ?? 0) !== 1) {
			$this->failJob($jobId, $response['desc'] ?? $this->l->t('Oops something went wrong.'));
			return new DataResponse($response);
		}

		// Scanning the extracted files into the file cache is a separate wait the
		// user should see, especially for archives with many small files.
		if ($jobId !== '') {
			$this->progressService->setPhase($this->userId, $jobId, ProgressService::PHASE_REGISTERING);
		}

		$this->postExtract($fileName, $directory, $extractTo, $tmpPath);

		try {
			// collect and return the properties of the resulting folder node
			$extractDir = '/' . trim($directory . '/' . $fileName, '/');
			$node = $this->userFolder->get($extractDir);
			$fileId = $node->getId();
			$owner = $node->getOwner()?->getUID();
			$permissions = $node->getPermissions();
			$mTime = $node->getMTime();
			$source = $this->urlGenerator->getBaseUrl() . '/remote.php/dav/files/' . $this->userId . "$extractDir";
			$root = '/files/' . $this->userId;
			$mountType = $node->getMountPoint()->getMountType();
			$ownerDisplayName = $node->getOwner()?->getDisplayName();

			$folder = [];
			$folder['fileId'] = $fileId;
			$folder['source'] = $source;
			$folder['root'] = $root;
			$folder['owner'] = $owner;
			$folder['permissions'] = $permissions;
			$folder['mtime'] = $mTime;
			$folder['mount-type'] = $mountType;
			$folder['owner-display-name'] = $ownerDisplayName;
			$response['extracted'] = $folder;

		} catch (NotFoundException $e) {
			$this->logger->debug(' - NotFoundException: ' . print_r($e->getMessage(), true));
			$this->failJob($jobId, $this->l->t('File not found'));
			return new DataResponse([], Http::STATUS_NOT_FOUND);
		} catch (InvalidPathException $e) {
			$this->logger->debug(' - InvalidPathException: ' . print_r($e->getMessage(), true));
			$this->failJob($jobId, $this->l->t('File not found'));
			return new DataResponse([], Http::STATUS_NOT_FOUND);
		}

		if ($jobId !== '') {
			$this->progressService->setPhase($this->userId, $jobId, ProgressService::PHASE_DONE);
		}

		return new DataResponse($response);
	}

	/**
	 * Current state of a running extraction.
	 *
	 * The extraction runs inside a single long POST, so this is a second request
	 * reading the state that request publishes. Job ids are scoped to the user,
	 * so one user cannot watch another user's extraction.
	 *
	 * @param string $jobId Id the client passed to the execute call
	 * @return DataResponse<Http::STATUS_OK, ExtractProgress, array{}>|DataResponse<Http::STATUS_NOT_FOUND, array<empty>, array{}>
	 *
	 * 200: Current progress
	 * 404: Unknown, expired or malformed job id
	 */
	#[ApiRoute(verb: 'GET', url: '/api/{apiVersion}/extraction/progress/{jobId}', requirements: ['apiVersion' => '(v1)'])]
	#[NoAdminRequired]
	public function progress(string $jobId): DataResponse {
		if (preg_match(self::JOB_ID_PATTERN, $jobId) !== 1) {
			return new DataResponse([], Http::STATUS_NOT_FOUND);
		}

		$state = $this->progressService->get($this->userId, $jobId);
		if ($state === null) {
			return new DataResponse([], Http::STATUS_NOT_FOUND);
		}

		/** @var ExtractProgress $state */
		return new DataResponse($state);
	}

	/**
	 * Build the callback the extraction service reports through, or null when
	 * this run is not being watched.
	 */
	private function progressReporter(string $jobId): ?callable {
		if ($jobId === '') {
			return null;
		}

		return function (float $percent, string $currentFile, int $filesDone, int $filesTotal) use ($jobId): void {
			$this->progressService->update($this->userId, $jobId, $percent, $currentFile, $filesDone, $filesTotal);
		};
	}

	/**
	 * Record why an extraction stopped, so the dialog can show it instead of
	 * waiting for a job that will never finish.
	 */
	private function failJob(string $jobId, string $error): void {
		if ($jobId === '') {
			return;
		}

		$this->progressService->setPhase($this->userId, $jobId, ProgressService::PHASE_ERROR, $error);
	}
}
